# Generated by Django 6.0.3 on 2026-03-11 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('passage_type', models.CharField(choices=[('informational', 'Informational Text'), ('argumentative', 'Argumentative Essay'), ('historical', 'Historical Document'), ('science', 'Science Article'), ('editorial', 'Editorial'), ('literary', 'Literary Nonfiction')], max_length=30)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('difficulty_label', models.CharField(max_length=50)),
                ('time_limit_minutes', models.IntegerField(default=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('drag_drop', 'Drag and Drop / Ordering'), ('text_analysis', 'Text Analysis'), ('editing', 'Editing and Revision'), ('extended_response', 'Extended Response')], default='multiple_choice', max_length=30)),
                ('skill_category', models.CharField(choices=[('reading_comprehension', 'Reading Comprehension'), ('argument_analysis', 'Argument Analysis'), ('grammar_editing', 'Grammar & Editing'), ('evidence_based', 'Evidence-Based Reasoning'), ('logical_reasoning', 'Logical Reasoning'), ('text_improvement', 'Text Improvement'), ('vocabulary', 'Vocabulary in Context'), ('structure_function', 'Structure & Function')], max_length=40)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation_correct', models.TextField()),
                ('explanation_a', models.TextField(blank=True)),
                ('explanation_b', models.TextField(blank=True)),
                ('explanation_c', models.TextField(blank=True)),
                ('explanation_d', models.TextField(blank=True)),
                ('difficulty_points', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam.passage')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.practicetest')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('raw_score', models.IntegerField(blank=True, null=True)),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('estimated_ged_score', models.IntegerField(blank=True, null=True)),
                ('reading_comprehension_score', models.FloatField(blank=True, null=True)),
                ('argument_analysis_score', models.FloatField(blank=True, null=True)),
                ('grammar_editing_score', models.FloatField(blank=True, null=True)),
                ('evidence_based_score', models.FloatField(blank=True, null=True)),
                ('logical_reasoning_score', models.FloatField(blank=True, null=True)),
                ('text_improvement_score', models.FloatField(blank=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
                ('flagged_questions', models.TextField(default='[]')),
                ('time_remaining_seconds', models.IntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.practicetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_score', models.IntegerField(default=190)),
                ('baseline_score', models.IntegerField(default=155)),
                ('study_streak_days', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('total_study_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.testattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
